### ISSUE TITLE
Compare to rio?

### ISSUE THREAD

**Issue by vi** [withoutboats/ringbahn#14]
This crate seems to be a competitor to [`rio`](https://crates.io/crates/rio).

`rio` should be mentioned in README somehow, ideally in some table that compares `ringbahn` and `rio`.

**Comment by withoutboats** [comment]
ringbahn and rio are fundamentally different approaches to the problem, comparisons between these are ultimately subjective in many ways. I don't like when libraries try to compare across these sort of deep differences because it never feels like it does justice to both approaches to the problem. I plan to write more soon about why I believe ringbahn's approach is the best approach to using io-uring from Rust.

Also, ringbahn is currently an experiment to demonstrate that a safe, zero-cost, ergonomic API for io-uring is possible within Rust's async ecosystem, but it is not production ready. So its not currently a competitor to any library which claims to be production ready.

**Comment by vi** [comment]
As a minimum there can be some `See also: rio - another approach to io_uring`.
